import { ModelMonthPayment } from "./modelMonthPayment";

export const Payment: ModelMonthPayment[] = [
    {
        id:"0",
        name: "Janvier",
        onePayment:[
            {
                id: "0",
                startDate: "2024-01-10",
                endDate: "",
                description: "Achat de nourriture",
                categories: "Alimentation",
                type: "Dépense",
                amount: -200,
                frequency: 0,
                user: {},
            },
            {
                id: "0",
                startDate: "2024-01-15",
                endDate: "",
                description: "Achat de nourriture",
                categories: "Paie",
                type: "Revenu",
                amount: 1500,
                frequency: 0,
                user: {},
            },
        ],
    },
    {
        id:"1",
        name: "Février",
        onePayment:[
            {
                id: "0",
                startDate: "2024-01-10",
                endDate: "",
                description: "Achat de nourriture",
                categories: "Alimentation",
                type: "Dépense",
                amount: -200,
                frequency: 0,
                user: {},
            },
            {
                id: "0",
                startDate: "2024-01-15",
                endDate: "",
                description: "Achat de nourriture",
                categories: "Paie",
                type: "Revenu",
                amount: 1500,
                frequency: 0,
                user: {},
            },
        ]
    },
    {
        id:"2",
        name: "Mars",
        onePayment:[
            {
                id: "0",
                startDate: "2024-01-10",
                endDate: "",
                description: "Achat de nourriture",
                categories: "Alimentation",
                type: "Dépense",
                amount: -200,
                frequency: 0,
                user: {},
            },
            {
                id: "0",
                startDate: "2024-01-15",
                endDate: "",
                description: "Achat de nourriture",
                categories: "Paie",
                type: "Revenu",
                amount: 1500,
                frequency: 0,
                user: {},
            },
        ]
    },
    {
        id:"3",
        name: "Avril",
        onePayment:[
            {
                id: "0",
                startDate: "2024-01-10",
                endDate: "",
                description: "Achat de nourriture",
                categories: "Alimentation",
                type: "Dépense",
                amount: -200,
                frequency: 0,
                user: {},
            },
            {
                id: "0",
                startDate: "2024-01-15",
                endDate: "",
                description: "Achat de nourriture",
                categories: "Paie",
                type: "Revenu",
                amount: 1500,
                frequency: 0,
                user: {},
            },
        ]
    },
    {
        id:"4",
        name: "Mai",
        onePayment:[
            {
                id: "0",
                startDate: "2024-01-10",
                endDate: "",
                description: "Achat de nourriture",
                categories: "Alimentation",
                type: "Dépense",
                amount: -200,
                frequency: 0,
                user: {},
            },
            {
                id: "0",
                startDate: "2024-01-15",
                endDate: "",
                description: "Achat de nourriture",
                categories: "Paie",
                type: "Revenu",
                amount: 1500,
                frequency: 0,
                user: {},
            },
        ]
    },
    {
        id:"5",
        name: "Juin",
        onePayment:[
            {
                id: "0",
                startDate: "2024-01-10",
                endDate: "",
                description: "Achat de nourriture",
                categories: "Alimentation",
                type: "Dépense",
                amount: -200,
                frequency: 0,
                user: {},
            },
            {
                id: "0",
                startDate: "2024-01-15",
                endDate: "",
                description: "Achat de nourriture",
                categories: "Paie",
                type: "Revenu",
                amount: 1500,
                frequency: 0,
                user: {},
            },
        ]
    },
    {
        id:"6",
        name: "Juilet",
        onePayment:[
            {
                id: "0",
                startDate: "2024-01-10",
                endDate: "",
                description: "Achat de nourriture",
                categories: "Alimentation",
                type: "Dépense",
                amount: -200,
                frequency: 0,
                user: {},
            },
            {
                id: "0",
                startDate: "2024-01-15",
                endDate: "",
                description: "Achat de nourriture",
                categories: "Paie",
                type: "Revenu",
                amount: 1500,
                frequency: 0,
                user: {},
            },
        ]
    },
    {
        id:"7",
        name: "Août",
        onePayment:[
            {
                id: "0",
                startDate: "2024-01-10",
                endDate: "",
                description: "Achat de nourriture",
                categories: "Alimentation",
                type: "Dépense",
                amount: -200,
                frequency: 0,
                user: {},
            },
            {
                id: "0",
                startDate: "2024-01-15",
                endDate: "",
                description: "Achat de nourriture",
                categories: "Paie",
                type: "Revenu",
                amount: 1500,
                frequency: 0,
                user: {},
            },
        ]
    },
    {
        id:"8",
        name: "Septembre",
        onePayment:[
            {
                id: "0",
                startDate: "2024-01-10",
                endDate: "",
                description: "Achat de nourriture",
                categories: "Alimentation",
                type: "Dépense",
                amount: -200,
                frequency: 0,
                user: {},
            },
            {
                id: "0",
                startDate: "2024-01-15",
                endDate: "",
                description: "Achat de nourriture",
                categories: "Paie",
                type: "Revenu",
                amount: 1500,
                frequency: 0,
                user: {},
            },
        ]
    },
    {
        id:"9",
        name: "Octobre",
        onePayment:[
            {
                id: "0",
                startDate: "2024-01-10",
                endDate: "",
                description: "Achat de nourriture",
                categories: "Alimentation",
                type: "Dépense",
                amount: -200,
                frequency: 0,
                user: {},
            },
            {
                id: "0",
                startDate: "2024-01-15",
                endDate: "",
                description: "Achat de nourriture",
                categories: "Paie",
                type: "Revenu",
                amount: 1500,
                frequency: 0,
                user: {},
            },
        ]
    },
    {
        id:"10",
        name: "Novembre",
        onePayment:[
            {
                id: "0",
                startDate: "2024-01-10",
                endDate: "",
                description: "Achat de nourriture",
                categories: "Alimentation",
                type: "Dépense",
                amount: -200,
                frequency: 0,
                user: {},
            },
            {
                id: "0",
                startDate: "2024-01-15",
                endDate: "",
                description: "Achat de nourriture",
                categories: "Paie",
                type: "Revenu",
                amount: 1500,
                frequency: 0,
                user: {},
            },
        ]
    },
    {
        id:"11",
        name: "Décembre",
        onePayment:[
            {
                id: "0",
                startDate: "2024-01-10",
                endDate: "",
                description: "Achat de nourriture",
                categories: "Alimentation",
                type: "Dépense",
                amount: -200,
                frequency: 0,
                user: {},
            },
            {
                id: "0",
                startDate: "2024-01-15",
                endDate: "",
                description: "Achat de nourriture",
                categories: "Paie",
                type: "Revenu",
                amount: 1500,
                frequency: 0,
                user: {},
            },
        ]
    },

]

export type { ModelMonthPayment };